services:
  database:
    image: 'postgres:15.0'
    ports:
      - '${DATABASE_EXPOSE}:5432'
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
    volumes:
      - database_data:/var/lib/postgresql/data

  web:
    image: 'ghcr.io/talkiiing-team/krabster:latest'
    ports:
      - '${WEB_EXPOSE}:3000'
    environment:
        SOVOK_SERVER_DATABASE_URL: postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@database:5432/${DATABASE_DB}
        SOVOK_SERVER_JWT_SECRET: ${SOVOK_SERVER_JWT_SECRET}
        SOVOK_SERVER_S3_SERVER: ${SOVOK_SERVER_S3_SERVER}
        SOVOK_SERVER_S3_BUCKET: ${SOVOK_SERVER_S3_BUCKET}
        SOVOK_SERVER_S3_REGION: ${SOVOK_SERVER_S3_REGION}
        SOVOK_SERVER_S3_ACCESS_KEY: ${SOVOK_SERVER_S3_ACCESS_KEY}
        SOVOK_SERVER_S3_SECRET_KEY: ${SOVOK_SERVER_S3_SECRET_KEY}
        SOVOK_SERVER_S3_ENDPOINT: ${SOVOK_SERVER_S3_ENDPOINT}
        SOVOK_SERVER_S3_FOLDER: ${SOVOK_SERVER_S3_FOLDER}

volumes:
  database_data:
